Texture changes and new logos
Gaelmare/WaterFlasks pull request #24
Opened 2024-09-03 17:05 UTC by Coach-mdl

Adjusted shading on the bladders and leather sac. Don't worry, no shape changes. Iron flasks have been given water levels like on the old 1.12 textures. I included a 3D iron waterflask in models if you want to experiment with a 3D model when you (V) place it but there's no obligation. It's a placeholder and can be changed. I don't know if it will even work but it would look nice in Firmalife jarbnets. I've included two logos. One is _something_ and the other looks more like the original. Your choice, I just included both to cover bases.

2024-09-23 22:32 UTC, Gaelmare requested changes
Texture paths for 3D model don't seem right?

2024-09-23 23:09 UTC, Coach-mdl commented
Where should I leave it?

2024-09-24 21:31 UTC, Coach-mdl commented
I went and removed the 3D model for now. Not needed right now.

2024-10-04 20:16 UTC, merged

2024-10-26 06:05 UTC, Gaelmare commented on src/main/resources/assets/waterflasks/textures/item/leather_flask.png
This isn't right, the full flask looks empty now.

2024-10-26 06:19 UTC, Gaelmare commented on src/main/resources/assets/waterflasks/textures/item/leather_flask.png
I've moved the flask textures around to make sense, but if you had time to contribute a different leather_flask-1.png that would show a difference between 20% and 40% full, that would be great!

2024-10-26 12:27 UTC, Coach-mdl commented on src/main/resources/assets/waterflasks/textures/item/leather_flask.png
Whoops. Misclicked. Don't worry I am about to do it